# Generated by Django 4.2.4 on 2023-09-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_sms_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_admin',
            new_name='created_by',
        ),
    ]
