# Generated by Django 4.2.4 on 2023-09-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_room_admin_room_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='rc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
    ]
