# Generated by Django 4.2.4 on 2023-09-14 10:59

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_rc'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='code',
            field=models.CharField(default=builtins.print, max_length=6),
            preserve_default=False,
        ),
    ]
